// ..\dev\assets\enems3.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_3 [];
#define MAX_ENEMS_TYPE_1_3 2
#define MAX_ENEMS_TYPE_2_3 3
#define MAX_ENEMS_TYPE_3_3 4

#define KILLABLE_ENEMS_3 9

extern const unsigned char hotspots_3 [];
#define MAX_HOTSPOTS_TYPE_0_3	5
#define MAX_HOTSPOTS_TYPE_1_3	11
