// ..\dev\assets\enems1.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_1 [];
#define MAX_ENEMS_TYPE_1_1 9
#define MAX_ENEMS_TYPE_2_1 11
#define MAX_ENEMS_TYPE_3_1 14

#define KILLABLE_ENEMS_1 34

extern const unsigned char hotspots_1 [];
#define MAX_HOTSPOTS_TYPE_0_1	9
#define MAX_HOTSPOTS_TYPE_1_1	20
#define MAX_HOTSPOTS_TYPE_3_1	6
