// rle44mapMK1(TM) map ..\dev\assets\map1.c
// Generated by rle44mapMK1.exe v0.4 [20181024]
// Copyleft 2015, 2017, 2018 The Mojon Twins

// Map Size Is 7x5
// Screen Size Is 16x12

// Compressed map structure, screens in RLE44, byte = NNNNRRRR, repeat R times tile #N
// Decos follow each screen, Format: [T N YX YX YX YX... (T < 128) | T YX (T >= 128)]

// Screen 00 is empty.
// Screen 01 is empty.
// Screen 02 is empty.
// Screen 03 is empty.
// Screen 04 is empty.
// Screen 05 is empty.
// Screen 06 is empty.
// Screen 07 is empty.
// Screen 08 is empty.
// Screen 09 is empty.
// Screen 0a is empty.
// Screen 0b is empty.
// Screen 0c is empty.
// Screen 0d is empty.
// Screen 0e is empty.
// Screen 0f is empty.
// Screen 10 is empty.
// Screen 11 is empty.
// Screen 12 is empty.
// Screen 13 is empty.
// Screen 14 is empty.
// Screen 15 is empty.
// Screen 16 is empty.
// Screen 17 is empty.
// Screen 18 is empty.
// Screen 19 is empty.
// Screen 1a is empty.
// Screen 1b is empty.
// Screen 1c is empty.
// Screen 1d is empty.
// Screen 1e is empty.
// Screen 1f is empty.
// Screen 20 is empty.
// Screen 21 is empty.
// Screen 22 is empty.

// Compressed map array

const unsigned char * const map_1 [] = {
	       0,        0,        0,        0,        0,        0,        0, 
	       0,        0,        0,        0,        0,        0,        0, 
	       0,        0,        0,        0,        0,        0,        0, 
	       0,        0,        0,        0,        0,        0,        0, 
	       0,        0,        0,        0,        0,        0,        0
};

// Total map size in bytes is 70
// From which, decorations size in bytes is 35

#define N_BOLTS_1 0
