// Generated by mkts_om v0.4.20181113
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char ss_pl_00 [];
extern const unsigned char ss_pl_01 [];
extern const unsigned char ss_pl_02 [];
extern const unsigned char ss_pl_03 [];
extern const unsigned char ss_pl_04 [];
extern const unsigned char ss_pl_05 [];
extern const unsigned char ss_pl_06 [];
extern const unsigned char ss_pl_07 [];
extern const unsigned char ss_pl_08 [];
extern const unsigned char ss_pl_09 [];
extern const unsigned char ss_pl_0a [];
extern const unsigned char ss_pl_0b [];
extern const unsigned char ss_pl_0c [];
extern const unsigned char ss_pl_0d [];
extern const unsigned char ss_pl_0e [];
extern const unsigned char ss_pl_0f [];

extern const unsigned char ss_en0_00 [];
extern const unsigned char ss_en0_01 [];
extern const unsigned char ss_en0_02 [];
extern const unsigned char ss_en0_03 [];
extern const unsigned char ss_en0_04 [];
extern const unsigned char ss_en0_05 [];

extern const unsigned char ss_en1_00 [];
extern const unsigned char ss_en1_01 [];
extern const unsigned char ss_en1_02 [];
extern const unsigned char ss_en1_03 [];
extern const unsigned char ss_en1_04 [];
extern const unsigned char ss_en1_05 [];

extern const unsigned char ss_plat_00 [];

extern const unsigned char ss_it_00 [];
extern const unsigned char ss_it_01 [];
extern const unsigned char ss_it_02 [];

extern const unsigned char ssALL_patterns_c [];
#define SSALL_PATTERNS_C_SIZE 1318

