// Generated by mkts_om v0.4.20181113
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char tsFONT_patterns_c [];
#define TSFONT_PATTERNS_C_SIZE 332

extern const unsigned char tsFONT_colours_c [];
#define TSFONT_COLOURS_C_SIZE 66

extern const unsigned char ts0_tmaps [];

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts2_tmaps [];

extern const unsigned char title_rle [];
#define TITLE_RLE_SIZE 511

extern const unsigned char title_cutout_paco [];
#define TITLE_CUTOUT_PACO_SIZE 160

extern const unsigned char title_cutout_puri [];
#define TITLE_CUTOUT_PURI_SIZE 160

extern const unsigned char cuts_rle [];
#define CUTS_RLE_SIZE 209

extern const unsigned char frame_rle [];
#define FRAME_RLE_SIZE 46

extern const unsigned char tsALL_patterns_c [];
#define TSALL_PATTERNS_C_SIZE 950

extern const unsigned char tsALL_colours_c [];
#define TSALL_COLOURS_C_SIZE 537

extern const unsigned char ending_rle [];
#define ENDING_RLE_SIZE 158

extern const unsigned char tsE_patterns_c [];
#define TSE_PATTERNS_C_SIZE 732

extern const unsigned char tsE_colours_c [];
#define TSE_COLOURS_C_SIZE 370

