// Generated by mkts_om v0.4.20181113
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char ts0_tmaps [];

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts2_tmaps [];

extern const unsigned char title_rle [];
#define TITLE_RLE_SIZE 511

extern const unsigned char title_cutout_paco [];
#define TITLE_CUTOUT_PACO_SIZE 160

extern const unsigned char title_cutout_puri [];
#define TITLE_CUTOUT_PURI_SIZE 160

extern const unsigned char cuts_rle [];
#define CUTS_RLE_SIZE 209

extern const unsigned char frame_rle [];
#define FRAME_RLE_SIZE 46

extern const unsigned char tsALL_patterns_c [];
#define TSALL_PATTERNS_C_SIZE 1183

extern const unsigned char tsALL_colours_c [];
#define TSALL_COLOURS_C_SIZE 579

