// ..\dev\assets\enems1.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_1 [];
#define MAX_ENEMS_TYPE_1_1 12
#define MAX_ENEMS_TYPE_2_1 21
#define MAX_ENEMS_TYPE_3_1 11
#define MAX_ENEMS_TYPE_4_1 6
#define MAX_ENEMS_TYPE_6_1 5

#define KILLABLE_ENEMS_1 49

extern const unsigned char hotspots_1 [];
#define MAX_HOTSPOTS_TYPE_0_1	6
#define MAX_HOTSPOTS_TYPE_1_1	0
#define MAX_HOTSPOTS_TYPE_2_1	1
#define MAX_HOTSPOTS_TYPE_3_1	3
#define MAX_HOTSPOTS_TYPE_4_1	14
