// rle44mapMK1(TM) map ..\dev\assets\map2.h
// Generated by rle44mapMK1.exe v0.4 [20181024]
// Copyleft 2015, 2017, 2018 The Mojon Twins

extern const unsigned char * const map_2 [];

#define N_BOLTS_2 2
extern const unsigned char map_2_locks [];

