// Generated by mkts_om v0.3.20181019
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char tsfont_patterns_c [];
#define TSFONT_PATTERNS_C_SIZE 309

extern const unsigned char tsfont_colours_c [];
#define TSFONT_COLOURS_C_SIZE 80

extern const unsigned char ts0_tmaps [];

extern const unsigned char ts0_patterns_c [];
#define TS0_PATTERNS_C_SIZE 519

extern const unsigned char ts0_colours_c [];
#define TS0_COLOURS_C_SIZE 263

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts1_patterns_c [];
#define TS1_PATTERNS_C_SIZE 870

extern const unsigned char ts1_colours_c [];
#define TS1_COLOURS_C_SIZE 513

extern const unsigned char ts2_tmaps [];

extern const unsigned char ts2_patterns_c [];
#define TS2_PATTERNS_C_SIZE 1065

extern const unsigned char ts2_colours_c [];
#define TS2_COLOURS_C_SIZE 727

