// ..\dev\assets\enems0.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_0 [];
#define MAX_ENEMS_TYPE_1_0 18
#define MAX_ENEMS_TYPE_2_0 13
#define MAX_ENEMS_TYPE_3_0 25
#define MAX_ENEMS_TYPE_4_0 2

#define KILLABLE_ENEMS_0 56

extern const unsigned char hotspots_0 [];
#define MAX_HOTSPOTS_TYPE_1_0	15
#define MAX_HOTSPOTS_TYPE_2_0	4
#define MAX_HOTSPOTS_TYPE_3_0	1
