// ..\dev\assets\enems1.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_1 [];
#define MAX_ENEMS_TYPE_1_1 10
#define MAX_ENEMS_TYPE_2_1 10
#define MAX_ENEMS_TYPE_3_1 25
#define MAX_ENEMS_TYPE_4_1 7

#define KILLABLE_ENEMS_1 45

extern const unsigned char hotspots_1 [];
#define MAX_HOTSPOTS_TYPE_0_1	3
#define MAX_HOTSPOTS_TYPE_1_1	15
#define MAX_HOTSPOTS_TYPE_3_1	2
