// rle53mapMK1(TM) map ..\dev\assets\map0.h
// Generated by rle53mapMK1.exe v0.4 [20181024]
// Copyleft 2015, 2017, 2018 The Mojon Twins

extern const unsigned char * const map_0 [];

#define N_BOLTS_0 4
extern const unsigned char map_0_locks [];

