// Generated by mkts_om v0.4.20181113
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char ss_pl_00 [];
extern const unsigned char ss_pl_01 [];
extern const unsigned char ss_pl_02 [];
extern const unsigned char ss_pl_03 [];
extern const unsigned char ss_pl_04 [];
extern const unsigned char ss_pl_05 [];
extern const unsigned char ss_pl_06 [];
extern const unsigned char ss_pl_07 [];
extern const unsigned char ss_pl_08 [];
extern const unsigned char ss_pl_09 [];

extern const unsigned char ss_ena_00 [];
extern const unsigned char ss_ena_01 [];

extern const unsigned char ss_enb_00 [];
extern const unsigned char ss_enb_01 [];

extern const unsigned char ss_enc_00 [];
extern const unsigned char ss_enc_01 [];

extern const unsigned char ss_plat_00 [];

extern const unsigned char ss_it_00 [];
extern const unsigned char ss_it_01 [];
extern const unsigned char ss_it_02 [];
extern const unsigned char ss_it_03 [];
extern const unsigned char ss_it_04 [];
extern const unsigned char ss_it_05 [];
extern const unsigned char ss_it_06 [];

extern const unsigned char ssALL_patterns_c [];
#define SSALL_PATTERNS_C_SIZE 1150

