// Generated by mkts_om v0.4.20181113
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char frame_rle [];
#define FRAME_RLE_SIZE 84

extern const unsigned char tsFONT_patterns_c [];
#define TSFONT_PATTERNS_C_SIZE 349

extern const unsigned char tsFONT_colours_c [];
#define TSFONT_COLOURS_C_SIZE 97

extern const unsigned char ts0_tmaps [];

extern const unsigned char ts0_patterns_c [];
#define TS0_PATTERNS_C_SIZE 335

extern const unsigned char ts0_colours_c [];
#define TS0_COLOURS_C_SIZE 219

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts1_patterns_c [];
#define TS1_PATTERNS_C_SIZE 596

extern const unsigned char ts1_colours_c [];
#define TS1_COLOURS_C_SIZE 289

extern const unsigned char title_rle [];
#define TITLE_RLE_SIZE 191

extern const unsigned char tsT_patterns_c [];
#define TST_PATTERNS_C_SIZE 10

extern const unsigned char tsT_colours_c [];
#define TST_COLOURS_C_SIZE 8

extern const unsigned char ending_rle [];
#define ENDING_RLE_SIZE 131

extern const unsigned char tsE_patterns_c [];
#define TSE_PATTERNS_C_SIZE 99

extern const unsigned char tsE_colours_c [];
#define TSE_COLOURS_C_SIZE 80

