// ..\dev\assets\enems2.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_2 [];
#define MAX_ENEMS_TYPE_1_2 6
#define MAX_ENEMS_TYPE_2_2 1
#define MAX_ENEMS_TYPE_3_2 6
#define MAX_ENEMS_TYPE_5_2 19
#define MAX_ENEMS_TYPE_7_2 29

#define KILLABLE_ENEMS_2 13

extern const unsigned char hotspots_2 [];
#define MAX_HOTSPOTS_TYPE_0_2	6
#define MAX_HOTSPOTS_TYPE_1_2	5
#define MAX_HOTSPOTS_TYPE_2_2	8
#define MAX_HOTSPOTS_TYPE_3_2	1
#define MAX_HOTSPOTS_TYPE_4_2	4
