// rle44mapMK1(TM) map ..\dev\assets\map1.h
// Generated by rle44mapMK1.exe v0.4 [20181024]
// Copyleft 2015, 2017, 2018 The Mojon Twins

extern const unsigned char * const map_1 [];

#define N_BOLTS_1 9
extern const unsigned char map_1_locks [];

