// Generated by mkts_om v0.3.20181019
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char ss_pl_00 [];
extern const unsigned char ss_pl_01 [];
extern const unsigned char ss_pl_02 [];
extern const unsigned char ss_pl_03 [];
extern const unsigned char ss_pl_04 [];
extern const unsigned char ss_pl_05 [];
extern const unsigned char ss_pl_06 [];
extern const unsigned char ss_pl_07 [];

extern const unsigned char ss_en_00 [];
extern const unsigned char ss_en_01 [];
extern const unsigned char ss_en_02 [];
extern const unsigned char ss_en_03 [];
extern const unsigned char ss_en_04 [];
extern const unsigned char ss_en_05 [];
extern const unsigned char ss_en_06 [];
extern const unsigned char ss_en_07 [];

extern const unsigned char ss_it_00 [];
extern const unsigned char ss_it_01 [];
extern const unsigned char ss_it_02 [];
extern const unsigned char ss_it_03 [];
extern const unsigned char ss_it_04 [];
extern const unsigned char ss_it_05 [];

extern const unsigned char ss_ss_00 [];
extern const unsigned char ss_ss_01 [];
extern const unsigned char ss_ss_02 [];
extern const unsigned char ss_ss_03 [];

extern const unsigned char ssALL_patterns_c [];
#define SSALL_PATTERNS_C_SIZE 1039

