// Generated by mkts_om v0.4.20181113
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char tsFONT_patterns_c [];
#define TSFONT_PATTERNS_C_SIZE 369

extern const unsigned char tsFONT_colours_c [];
#define TSFONT_COLOURS_C_SIZE 67

extern const unsigned char ts0_tmaps [];

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts2_tmaps [];

extern const unsigned char title_rle [];
#define TITLE_RLE_SIZE 534

extern const unsigned char cuts_rle [];
#define CUTS_RLE_SIZE 297

extern const unsigned char frame_rle [];
#define FRAME_RLE_SIZE 87

extern const unsigned char tsALL_patterns_c [];
#define TSALL_PATTERNS_C_SIZE 0

extern const unsigned char tsALL_colours_c [];
#define TSALL_COLOURS_C_SIZE 0

