// Generated by mkts_om v0.3.20181019
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char tsfont_patterns_c [];
#define TSFONT_PATTERNS_C_SIZE 363

extern const unsigned char tsfont_colours_c [];
#define TSFONT_COLOURS_C_SIZE 69

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts2_tmaps [];

extern const unsigned char title_rle [];
#define TITLE_RLE_SIZE 515

extern const unsigned char cuts_rle [];
#define CUTS_RLE_SIZE 295

extern const unsigned char frame_rle [];
#define FRAME_RLE_SIZE 85

extern const unsigned char tsALL_patterns_c [];
#define TSALL_PATTERNS_C_SIZE 1028

extern const unsigned char ts2_colours_c [];
#define TS2_COLOURS_C_SIZE 712

