// ..\dev\assets\enems0.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_0 [];
#define MAX_ENEMS_TYPE_1_0 16
#define MAX_ENEMS_TYPE_2_0 7
#define MAX_ENEMS_TYPE_3_0 7
#define MAX_ENEMS_TYPE_4_0 1
#define MAX_ENEMS_TYPE_7_0 38

#define KILLABLE_ENEMS_0 30

extern const unsigned char hotspots_0 [];
#define MAX_HOTSPOTS_TYPE_0_0	1
#define MAX_HOTSPOTS_TYPE_1_0	5
#define MAX_HOTSPOTS_TYPE_2_0	7
#define MAX_HOTSPOTS_TYPE_4_0	11
