// ..\dev\assets\enems0.h
// Generated by eneexp3.exe v0.3 [20181023]
// Copyleft 2016, 2018 The Mojon Twins

extern const unsigned char enems_0 [];
#define MAX_ENEMS_TYPE_1_0 13
#define MAX_ENEMS_TYPE_2_0 21
#define MAX_ENEMS_TYPE_3_0 20
#define MAX_ENEMS_TYPE_4_0 8

#define KILLABLE_ENEMS_0 54

extern const unsigned char hotspots_0 [];
#define MAX_HOTSPOTS_TYPE_0_0	6
#define MAX_HOTSPOTS_TYPE_1_0	0
#define MAX_HOTSPOTS_TYPE_2_0	2
#define MAX_HOTSPOTS_TYPE_3_0	4
#define MAX_HOTSPOTS_TYPE_4_0	12
