// rle44mapMK1(TM) map ..\dev\assets\map3.h
// Generated by rle44mapMK1.exe v0.4 [20181024]
// Copyleft 2015, 2017, 2018 The Mojon Twins

extern const unsigned char * const map_3 [];

#define N_BOLTS_3 4
extern const unsigned char map_3_locks [];

