// Generated by mkts_om v0.5.20190909
// Copyleft 2017-2019 The Mojon Twins

extern const unsigned char ss_pl_00 [];
extern const unsigned char ss_pl_01 [];
extern const unsigned char ss_pl_02 [];
extern const unsigned char ss_pl_03 [];
extern const unsigned char ss_pl_04 [];
extern const unsigned char ss_pl_05 [];
extern const unsigned char ss_pl_06 [];
extern const unsigned char ss_pl_07 [];

extern const unsigned char ss_fanty_00 [];
extern const unsigned char ss_fanty_01 [];
extern const unsigned char ss_fanty_02 [];
extern const unsigned char ss_fanty_03 [];

extern const unsigned char ss_plat_00 [];
extern const unsigned char ss_plat_01 [];

extern const unsigned char ss_it_00 [];
extern const unsigned char ss_it_01 [];
extern const unsigned char ss_it_02 [];
extern const unsigned char ss_it_03 [];
extern const unsigned char ss_it_04 [];
extern const unsigned char ss_it_05 [];
extern const unsigned char ss_it_06 [];

extern const unsigned char ss_fixed_patterns_c [];
#define SS_FIXED_PATTERNS_C_SIZE 847

extern const unsigned char ss_en_0_00 [];
extern const unsigned char ss_en_0_01 [];
extern const unsigned char ss_en_0_02 [];
extern const unsigned char ss_en_0_03 [];
extern const unsigned char ss_en_0_04 [];
extern const unsigned char ss_en_0_05 [];
extern const unsigned char ss_en_0_06 [];
extern const unsigned char ss_en_0_07 [];
extern const unsigned char ss_en_0_08 [];
extern const unsigned char ss_en_0_09 [];
extern const unsigned char ss_en_0_0a [];
extern const unsigned char ss_en_0_0b [];

extern const unsigned char ss_en_0_patterns_c [];
#define SS_EN_0_PATTERNS_C_SIZE 507

extern const unsigned char ss_en_1_00 [];
extern const unsigned char ss_en_1_01 [];
extern const unsigned char ss_en_1_02 [];
extern const unsigned char ss_en_1_03 [];
extern const unsigned char ss_en_1_04 [];
extern const unsigned char ss_en_1_05 [];
extern const unsigned char ss_en_1_06 [];
extern const unsigned char ss_en_1_07 [];
extern const unsigned char ss_en_1_08 [];
extern const unsigned char ss_en_1_09 [];
extern const unsigned char ss_en_1_0a [];
extern const unsigned char ss_en_1_0b [];

extern const unsigned char ss_en_1_patterns_c [];
#define SS_EN_1_PATTERNS_C_SIZE 518

extern const unsigned char ss_en_2_00 [];
extern const unsigned char ss_en_2_01 [];
extern const unsigned char ss_en_2_02 [];
extern const unsigned char ss_en_2_03 [];
extern const unsigned char ss_en_2_04 [];
extern const unsigned char ss_en_2_05 [];
extern const unsigned char ss_en_2_06 [];
extern const unsigned char ss_en_2_07 [];
extern const unsigned char ss_en_2_08 [];
extern const unsigned char ss_en_2_09 [];

extern const unsigned char ss_en_2_patterns_c [];
#define SS_EN_2_PATTERNS_C_SIZE 504

