// Generated by mkts_om v0.5.20190909
// Copyleft 2017-2019 The Mojon Twins

extern const unsigned char tsfont_patterns_c [];
#define TSFONT_PATTERNS_C_SIZE 317

extern const unsigned char tsfont_colours_c [];
#define TSFONT_COLOURS_C_SIZE 86

extern const unsigned char hud_rle [];
#define HUD_RLE_SIZE 39

extern const unsigned char title_rle [];
#define TITLE_RLE_SIZE 506

extern const unsigned char tstitle_patterns_c [];
#define TSTITLE_PATTERNS_C_SIZE 348

extern const unsigned char tstitle_colours_c [];
#define TSTITLE_COLOURS_C_SIZE 182

extern const unsigned char ending_rle [];
#define ENDING_RLE_SIZE 161

extern const unsigned char tsending_patterns_c [];
#define TSENDING_PATTERNS_C_SIZE 730

extern const unsigned char tsending_colours_c [];
#define TSENDING_COLOURS_C_SIZE 439

extern const unsigned char ts0_tmaps [];

extern const unsigned char ts0_patterns_c [];
#define TS0_PATTERNS_C_SIZE 507

extern const unsigned char ts0_colours_c [];
#define TS0_COLOURS_C_SIZE 272

extern const unsigned char ts1_tmaps [];

extern const unsigned char ts1_patterns_c [];
#define TS1_PATTERNS_C_SIZE 418

extern const unsigned char ts1_colours_c [];
#define TS1_COLOURS_C_SIZE 270

extern const unsigned char ts2_tmaps [];

extern const unsigned char ts2_patterns_c [];
#define TS2_PATTERNS_C_SIZE 538

extern const unsigned char ts2_colours_c [];
#define TS2_COLOURS_C_SIZE 293

extern const unsigned char ts3_tmaps [];

extern const unsigned char ts3_patterns_c [];
#define TS3_PATTERNS_C_SIZE 379

extern const unsigned char ts3_colours_c [];
#define TS3_COLOURS_C_SIZE 211

