// Generated by mkts_om v0.3.20181019
// Copyleft 2017, 2018 The Mojon Twins

extern const unsigned char ss_pl_00 [];
extern const unsigned char ss_pl_01 [];
extern const unsigned char ss_pl_02 [];
extern const unsigned char ss_pl_03 [];
extern const unsigned char ss_pl_04 [];
extern const unsigned char ss_pl_05 [];
extern const unsigned char ss_pl_06 [];
extern const unsigned char ss_pl_07 [];

extern const unsigned char ss_fanty_00 [];
extern const unsigned char ss_fanty_01 [];
extern const unsigned char ss_fanty_02 [];
extern const unsigned char ss_fanty_03 [];

extern const unsigned char ss_plat_00 [];
extern const unsigned char ss_plat_01 [];

extern const unsigned char ss_it_00 [];
extern const unsigned char ss_it_01 [];
extern const unsigned char ss_it_02 [];
extern const unsigned char ss_it_03 [];
extern const unsigned char ss_it_04 [];
extern const unsigned char ss_it_05 [];

extern const unsigned char ss_fixed_patterns_c [];
#define SS_FIXED_PATTERNS_C_SIZE 853

extern const unsigned char ss_en_0_00 [];
extern const unsigned char ss_en_0_01 [];
extern const unsigned char ss_en_0_02 [];
extern const unsigned char ss_en_0_03 [];
extern const unsigned char ss_en_0_04 [];
extern const unsigned char ss_en_0_05 [];
extern const unsigned char ss_en_0_06 [];
extern const unsigned char ss_en_0_07 [];
extern const unsigned char ss_en_0_08 [];
extern const unsigned char ss_en_0_09 [];
extern const unsigned char ss_en_0_0a [];
extern const unsigned char ss_en_0_0b [];
extern const unsigned char ss_en_0_0c [];
extern const unsigned char ss_en_0_0d [];
extern const unsigned char ss_en_0_0e [];
extern const unsigned char ss_en_0_0f [];
extern const unsigned char ss_en_0_10 [];
extern const unsigned char ss_en_0_11 [];

extern const unsigned char ss_en_0_patterns_c [];
#define SS_EN_0_PATTERNS_C_SIZE 542

extern const unsigned char ss_en_1_00 [];
extern const unsigned char ss_en_1_01 [];
extern const unsigned char ss_en_1_02 [];
extern const unsigned char ss_en_1_03 [];
extern const unsigned char ss_en_1_04 [];
extern const unsigned char ss_en_1_05 [];
extern const unsigned char ss_en_1_06 [];
extern const unsigned char ss_en_1_07 [];
extern const unsigned char ss_en_1_08 [];
extern const unsigned char ss_en_1_09 [];
extern const unsigned char ss_en_1_0a [];
extern const unsigned char ss_en_1_0b [];
extern const unsigned char ss_en_1_0c [];
extern const unsigned char ss_en_1_0d [];
extern const unsigned char ss_en_1_0e [];
extern const unsigned char ss_en_1_0f [];
extern const unsigned char ss_en_1_10 [];
extern const unsigned char ss_en_1_11 [];
extern const unsigned char ss_en_1_12 [];
extern const unsigned char ss_en_1_13 [];
extern const unsigned char ss_en_1_14 [];
extern const unsigned char ss_en_1_15 [];
extern const unsigned char ss_en_1_16 [];
extern const unsigned char ss_en_1_17 [];
extern const unsigned char ss_en_1_18 [];
extern const unsigned char ss_en_1_19 [];
extern const unsigned char ss_en_1_1a [];
extern const unsigned char ss_en_1_1b [];
extern const unsigned char ss_en_1_1c [];
extern const unsigned char ss_en_1_1d [];

extern const unsigned char ss_en_1_patterns_c [];
#define SS_EN_1_PATTERNS_C_SIZE 550

extern const unsigned char ss_en_2_00 [];
extern const unsigned char ss_en_2_01 [];
extern const unsigned char ss_en_2_02 [];
extern const unsigned char ss_en_2_03 [];
extern const unsigned char ss_en_2_04 [];
extern const unsigned char ss_en_2_05 [];
extern const unsigned char ss_en_2_06 [];
extern const unsigned char ss_en_2_07 [];
extern const unsigned char ss_en_2_08 [];
extern const unsigned char ss_en_2_09 [];
extern const unsigned char ss_en_2_0a [];
extern const unsigned char ss_en_2_0b [];
extern const unsigned char ss_en_2_0c [];
extern const unsigned char ss_en_2_0d [];
extern const unsigned char ss_en_2_0e [];
extern const unsigned char ss_en_2_0f [];
extern const unsigned char ss_en_2_10 [];
extern const unsigned char ss_en_2_11 [];
extern const unsigned char ss_en_2_12 [];
extern const unsigned char ss_en_2_13 [];
extern const unsigned char ss_en_2_14 [];
extern const unsigned char ss_en_2_15 [];
extern const unsigned char ss_en_2_16 [];
extern const unsigned char ss_en_2_17 [];
extern const unsigned char ss_en_2_18 [];
extern const unsigned char ss_en_2_19 [];
extern const unsigned char ss_en_2_1a [];
extern const unsigned char ss_en_2_1b [];
extern const unsigned char ss_en_2_1c [];
extern const unsigned char ss_en_2_1d [];
extern const unsigned char ss_en_2_1e [];
extern const unsigned char ss_en_2_1f [];
extern const unsigned char ss_en_2_20 [];
extern const unsigned char ss_en_2_21 [];
extern const unsigned char ss_en_2_22 [];
extern const unsigned char ss_en_2_23 [];
extern const unsigned char ss_en_2_24 [];
extern const unsigned char ss_en_2_25 [];
extern const unsigned char ss_en_2_26 [];
extern const unsigned char ss_en_2_27 [];

extern const unsigned char ss_en_2_patterns_c [];
#define SS_EN_2_PATTERNS_C_SIZE 521

